#Gradle
org.gradle.jvmargs=-Xmx2048M -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options\="-Xmx2048M"
systemProp.org.gradle.internal.http.connectionTimeout=180000
systemProp.org.gradle.internal.http.socketTimeout=180000
#Kotlin
kotlin.code.style=official
#Android
android.useAndroidX=true
android.nonTransitiveRClass=true
#MPP
kotlin.mpp.enableCInteropCommonization=true
kotlin.mpp.androidSourceSetLayoutVersion=2
ksp.incremental=false
#Publish
MODULE_NAME=KuiklyChart
MAVEN_VERSION=1.2.1
GROUP_ID=com.tencent.kuiklybase
KOTLIN_VERSION_LIST=2.1.21
OHOS_KOTLIN_VERSION_LIST=2.0.21-KBA-010
MAVEN_REPO_URL=
MAVEN_USERNAME=
MAVEN_PASSWORD=
